[package]
name = "tg_webapp_init_data"
version = "0.1.0"
edition = "2024"

[dependencies]
form_urlencoded = "1.2.1"
hmac-sha256 = "1.1.8"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
